name: deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_PATH: ~/${{ secrets.SSH_HOST }}/nodejs_app/www/
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: 1024
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Copy files to the server
        run: |
          rsync -a --progress --human-readable --delete -e "ssh -p $SSH_PORT" \
          --exclude-from '.gitignore' \
          --include-from .deploylist \
          --exclude public \
          --exclude README.md \
          . $SSH_USER@$SSH_HOST:$DEPLOY_PATH
      - name: Install dependencies
        run: |
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd $DEPLOY_PATH && npm install"

  restart:
    needs: deploy
    runs-on: ubuntu-latest
    env:
      RESTART_PATH: ~/${{ secrets.SSH_HOST }}/nodejs_tmp/www/
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: 1024
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: SHow key
        run: echo $secrets.SSH_PRIVATE_KEY
      - name: Add restart file
        run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd $DEPLOY_PATH && touch always_restart.txt"
      - name: Touch site
        run: |
          status_code=$(curl -I --write-out "%{http_code}" --silent --output /dev/null "https://$SSH_HOST")
          echo $status_code
          sleep 3
          status_code=$(curl -I --write-out "%{http_code}" --silent --output /dev/null "https://$SSH_HOST")
          echo $status_code
      - name: Delete restart file
        run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd $DEPLOY_PATH && rm always_restart.txt"
